### ISSUE TITLE
Error in C4D Octane "<node 'Vectron'>:2: error: error: could not find include file: ff-vectron.h" 

### ISSUE THREAD

**Issue by smelvin0** [thargor6/FFVectron#4]
Probably my issue, but it's been driving me nuts and I really want to use your amazing scripts! 

Get an error }<node 'Vectron'>:2: error: error: could not find include file: ff-vectron.h", while trying to use them in C4D and Octane. I loaded the files including the ff-vectron.h file in the default folder for octane but still no luck. Any help would be amazing, new to using code in design

![image](https://user-images.githubusercontent.com/5642028/110274911-eeec7900-7f9d-11eb-9391-2b028aace009.png)

**Comment by verstaerkermusic** [comment]
Hi

thats easy, just include the full-path to the file ( ff-vectron.h) or the content of the file   .. but the first solution is easier

**Comment by thargor6** [comment]
some host applications jsut do not support include files well. At least the second solution, as described by verstaerkermusic above, should work. Maybe you can ask the maintainer of your tool that they improve the support for external include files.
